const Data = [
  {
    id: 1,
    doctorName: "Dr. John Smith",
    img: "./public/ahmet.png",
    expertiseField: "Cardiology",
    email: "john.smith@example.com",
    telNumber: "+1234567890",
    patients: [
      {
        id: 1,
        patientName: "John Doe",
        appointmentDate: "2024-05-10",
        isSeen: true,
        concerns: "Chest pain and shortness of breath",
        patientDoc: 1,
        referral: true,
        DOB: "1988-03-15",
      },
      {
        id: 2,
        patientName: "Jane Smith",
        appointmentDate: "2024-03-15",
        isSeen: false,
        concerns: "High blood pressure and headaches",
        patientDoc: 1,
        referral: false,
        DOB: "1988-03-15",
      },
      {
        id: 3,
        patientName: "John Doe",
        appointmentDate: "2024-03-10",
        isSeen: true,
        concerns: "Chest pain and shortness of breath",
        patientDoc: 1,
        referral: true,
        DOB: "1988-03-15",
      },
      {
        id: 4,
        patientName: "Jane Smith",
        appointmentDate: "2024-06-15",
        isSeen: false,
        concerns: "High blood pressure and headaches",
        patientDoc: 1,
        referral: false,
        DOB: "1988-03-15",
      },
    ],
  },
  {
    id: 2,
    doctorName: "Dr. Emily Johnson",
    img: "./public/ahmet.png",
    expertiseField: "Pediatrics",
    email: "emily.johnson@example.com",
    telNumber: "+1987654321",
    patients: [
      {
        id: 1,
        patientName: "Michael Brown",
        appointmentDate: "2024-03-12",
        isSeen: false,
        concerns: "Fever and cough",
        patientDoc: 2,
        referral: false,
        DOB: "1988-03-15",
      },
      {
        id: 2,
        patientName: "Emma Green",
        appointmentDate: "2024-03-18",
        isSeen: true,
        concerns: "Stomach pain and vomiting",
        patientDoc: 2,
        referral: true,
        DOB: "1988-03-15",
      },
    ],
  },
  {
    id: 3,
    doctorName: "Dr. Michael Brown",
    img: "./public/ahmet.png",
    expertiseField: "Orthopedics",
    email: "michael.brown@example.com",
    telNumber: "+1122334455",
    patients: [
      {
        id: 1,
        patientName: "Liam Johnson",
        appointmentDate: "2024-03-19",
        isSeen: false,
        concerns: "Fractured arm",
        patientDoc: 3,
        referral: false,
        DOB: "1988-03-15",
      },
      {
        id: 2,
        patientName: "Olivia Clark",
        appointmentDate: "2024-03-23",
        isSeen: true,
        concerns: "Back pain",
        patientDoc: 3,
        referral: true,
        DOB: "1988-03-15",
      },
    ],
  },
  {
    id: 4,
    doctorName: "Dr. Sarah White",
    img: "./public/ahmet.png",
    expertiseField: "Dermatology",
    email: "sarah.white@example.com",
    telNumber: "+9988776655",
    patients: [
      {
        id: 1,
        patientName: "Ethan Miller",
        appointmentDate: "2024-03-21",
        isSeen: true,
        concerns: "Skin rash",
        patientDoc: 4,
        referral: true,
        DOB: "1988-03-15",
      },
      {
        id: 2,
        patientName: "Ava Wilson",
        appointmentDate: "2024-03-25",
        isSeen: false,
        concerns: "Acne",
        patientDoc: 4,
        referral: false,
        DOB: "1988-03-15",
      },
    ],
  },
  {
    id: 5,
    doctorName: "Dr. Olivia Martinez",
    img: "./public/ahmet.png",
    expertiseField: "Neurology",
    email: "olivia.martinez@example.com",
    telNumber: "+3344556677",
    patients: [
      {
        id: 1,
        patientName: "Noah Anderson",
        appointmentDate: "2024-03-22",
        isSeen: false,
        concerns: "Headaches and dizziness",
        patientDoc: 5,
        referral: false,
        DOB: "1988-03-15",
      },
      {
        id: 2,
        patientName: "Sophia Thomas",
        appointmentDate: "2024-03-26",
        isSeen: true,
        concerns: "Memory loss",
        patientDoc: 5,
        referral: true,
        DOB: "1988-03-15",
      },
    ],
  },
  {
    id: 6,
    doctorName: "Dr. Olivia Martinez",
    img: "./public/ahmet.png",
    expertiseField: "Neurology",
    email: "olivia.martinez@example.com",
    telNumber: "+3344556677",
    patients: [
      {
        id: 1,
        patientName: "Noah Anderson",
        appointmentDate: "2024-03-22",
        isSeen: false,
        concerns: "Headaches and dizziness",
        patientDoc:6,
        referral: false,
        DOB: "1988-03-15",
      },
      {
        id: 2,
        patientName: "Sophia Thomas",
        appointmentDate: "2024-03-26",
        isSeen: true,
        concerns: "Memory loss",
        patientDoc:6,
        referral: true,
        DOB: "1988-03-15",
      },
    ],
  },
];

export default Data;
